### ISSUE TITLE
Аватарки авторов в Списке статей при увеличении оказываются перекрыты чужими аватарками и элементами таблицы

### ISSUE THREAD

**Issue by MaestroGame** [SCPru/RuFoundation#183]
Решением проблемы стали бы следующие два правила: 

```CSS
.printuser.avatarhover a:hover img.small, .printuser span:hover img.small {
  z-index: 100;
  position: relative;
}
```

Для потребностей структуры z-index можно было бы сделать другим числом.
